apiVersion: v1
kind: Secret
metadata:
  name: nexify-secrets
  namespace: nexify
type: Opaque
stringData:
  APP_SECRET: "8K3mP9nR2vX5cZ7wQ1tY4uH6gF0sA2dL"
  JWT_SECRET_KEY: "p!7#:d'mPxhvb/yBLu]4c5K2i[$9A(06"
  JWT_PUBLIC_KEY: "p!7#:d'mPxhvb/yBLu]4c5K2i[$9A(06"
  JWT_PASSPHRASE: "j+bQ~'DpBMv/LJ:`2YGhy$}EV0|O(\"wZ"
  DATABASE_PASSWORD: "nexify123"
  GOOGLE_API_KEY: "AIzaSyDm8ZWxyKxBzLmNwhJSomz2Ii68TbkRlOQ"
